### ISSUE TITLE
graphical parameters

### ISSUE THREAD

**Issue by ajwhipple** [CharlesJB/metagene#118]
Is there a way to modify the graphical parameters of the mg$plot()?  For example, I'd like to adjust the y-axis scale to make if the same between several plots.
Thanks for any help!

**Comment by ericfournier2** [comment]
Hello ajwhipple,

you can call the get_plot() method to access the last ggplot object generated by metagene. You can then pass additional parameters tot it. For example:

mg = metagene::get_demo_metagene()
mg$plot()

gg_object = mg$get_plot()
print(gg_object + ylim(0,50)

Hope this help,
-Eric

**Comment by ajwhipple** [comment]
Perfect! Thanks Eric!

**Comment by ajwhipple** [comment]
Another question, thanks for your patience.  I'm trying to trace back individual regions in my bam file that have the strongest contributions to the metagene plot.  I believe mg$get_matrices() gives me the normalized RPM for each region in each bin. Are the rows of the this matrix in the same order as the original bam file in such a way that I can re-merge the tables?
--Amanda

**Comment by ericfournier2** [comment]
Hello Amanda,

yes, the rows of the matrix should be in the correct order. However, there's currently an issue with the matrices not respecting the flip_regions() parameter (Issue #104). So you might need to do that yourself if the orientation of your regions is important.

Alternatively, you might want to try out our prototype for the next version of metagene, metagene2 (https://github.com/ArnaudDroitLab/metagene2). The above mentionned bug has been corrected, and we also have a method for plotting single regions. It's still in development, so there are a few rough edges, but maybe the added functionality would be useful to you.

Cheers,
-Eric
