### ISSUE TITLE
regions <- regions

### ISSUE THREAD

**Issue by adeschen** [CharlesJB/metagene#36]
In metagene$prepare_regions, is the second "else if" useful ? Is it a implicite assignation to a private variable ?

prepare_regions = function(regions) {
if (class(regions) == "character") {
names <- sapply(regions, function(x) file_path_sans_ext(basename(x)))
regions <- private$parallel_job$launch_job(data = regions,
FUN = import)
names(regions) <- names
} else if (class(regions) == "GRanges") {
regions <- GRangesList(regions = regions)
} else if (class(regions) == "GRangesList") {
regions <- regions
}

**Comment by CharlesJB** [comment]
Considering that there is a validity check in the check_param function and that prepare_regions is private, there is no need for the last else if.
